apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sporedb.fullname" . }}
  labels:
    {{- include "sporedb.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ printf "postgresql+asyncpg://sporedb:%s@%s-postgresql:5432/sporedb" .Values.postgresql.auth.password (include "sporedb.fullname" .) | b64enc | quote }}
  {{- if .Values.secrets.jwtPrivateKey }}
  jwt-private-key: {{ .Values.secrets.jwtPrivateKey | b64enc | quote }}
  {{- else }}
  jwt-private-key: {{ "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtPublicKey }}
  jwt-public-key: {{ .Values.secrets.jwtPublicKey | b64enc | quote }}
  {{- else }}
  jwt-public-key: {{ "" | b64enc | quote }}
  {{- end }}
