name: Deploy Docs
on:
  push:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.12"
      - run: pip install mkdocs-material "mkdocstrings[python]"
      - run: pip install -e ".[cloud]"
      - run: mkdocs gh-deploy --force
